version: 2

sources:
  - name: raw_data
    description: Raw data sources
    database: retail_db
    schema: raw
    tables:
      - name: sales
        description: sales_data
        columns:
          - name: customer_id
            tests:
              - not_null
